//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlinesMaster
    {
        public int Id { get; set; }
        public string AirlinesName { get; set; }
        public string ReportType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
