//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int Id { get; set; }
        public Nullable<int> ExpenseCategoryId { get; set; }
        public string ExpenseCategoryName { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public string ExpenseRemarks { get; set; }
        public Nullable<int> UmrahGroupId { get; set; }
        public Nullable<int> BookingRefId { get; set; }
        public string TypeofBooking { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
    }
}
