//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int Id { get; set; }
        public Nullable<int> BookingRefNo { get; set; }
        public string TypeofBooking { get; set; }
        public string SubTypeofBooking { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string MobileNumber { get; set; }
        public string SupplierGST { get; set; }
        public string ToAddress { get; set; }
        public Nullable<int> InvoiceCreatedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
    }
}
