//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> SalesEntryId { get; set; }
        public string CompanyGSTId { get; set; }
        public string OwnGSTNumber { get; set; }
        public string StateName { get; set; }
        public string TotalAmount { get; set; }
        public string TotalGSTAmount { get; set; }
        public string PanNumber { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<System.DateTime> ActivationUpto { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
    }
}
