//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSHistory
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string JourneyFrom { get; set; }
        public string JourneyTo { get; set; }
        public string TicketNumber { get; set; }
        public string SeatNumbers { get; set; }
        public Nullable<System.DateTime> DepartureOn { get; set; }
        public Nullable<System.DateTime> ArrivalOn { get; set; }
        public Nullable<bool> IsSMSSent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ChangedBy { get; set; }
        public string ChangedByName { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string DeletedBy { get; set; }
        public string DeletedByName { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
