//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSPricingMaster
    {
        public int Id { get; set; }
        public string NotificationCategory { get; set; }
        public Nullable<decimal> NotificationPrice { get; set; }
        public Nullable<int> CharacterLimit { get; set; }
    }
}
