//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbookticket
    {
        public long ID { get; set; }
        public long CompanyID { get; set; }
        public string Fromlocation { get; set; }
        public string Tolocation { get; set; }
        public Nullable<System.DateTime> Dateofjourney { get; set; }
        public string Mobilenumber { get; set; }
        public string Emailid { get; set; }
        public string Departuretime { get; set; }
        public string Arrivaltime { get; set; }
        public string Busnumber { get; set; }
        public string Seatnumber { get; set; }
        public string Bustype { get; set; }
        public Nullable<decimal> Ticketfare { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> Servicechqarge { get; set; }
        public Nullable<decimal> Totalfare { get; set; }
        public string Operatorname { get; set; }
        public string Operatorcntno { get; set; }
        public string Boardingpoint { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Refoundamount { get; set; }
        public string OperaterPNR { get; set; }
        public Nullable<decimal> CommissionToAgent { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
    }
}
