//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHirebusbykm
    {
        public long HirebusbykmID { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string Nameofhirer { get; set; }
        public Nullable<System.DateTime> Bookingdate { get; set; }
        public string Address { get; set; }
        public string Partyphonumbers { get; set; }
        public string Particularsofjourney { get; set; }
        public string Startingfrom { get; set; }
        public string Goingto { get; set; }
        public string Startingtime { get; set; }
        public Nullable<System.DateTime> Startingdate { get; set; }
        public string Endingtime { get; set; }
        public Nullable<System.DateTime> Endingdate { get; set; }
        public string Vehicle { get; set; }
        public string Vehicletype { get; set; }
        public Nullable<long> Noofvehicles { get; set; }
        public string Vehiclenumbers { get; set; }
        public Nullable<long> Seetingcapacity { get; set; }
        public Nullable<decimal> Roadtax { get; set; }
        public Nullable<decimal> Noofkm { get; set; }
        public Nullable<decimal> Priceperkm { get; set; }
        public Nullable<decimal> Hireamount { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Driverperday { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Waitingcharges { get; set; }
        public string Per { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<int> NoOfDrivers { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string StartingMinutes { get; set; }
        public string EndingMinutes { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ExtraCharges { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
    }
}
