//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackagebookingdomestic
    {
        public long PBDID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Custmername { get; set; }
        public string Mobilenumber { get; set; }
        public string IDProof { get; set; }
        public string IdProofNumber { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Startingdate { get; set; }
        public Nullable<System.DateTime> Endingdate { get; set; }
        public string Sightseeingby { get; set; }
        public Nullable<long> Numberofadults { get; set; }
        public Nullable<long> numberofchildren { get; set; }
        public string HotelRequired { get; set; }
        public string Hotel { get; set; }
        public string HotelType { get; set; }
        public string Roomtype { get; set; }
        public Nullable<long> Noofrooms { get; set; }
        public string Paclageparticulars { get; set; }
        public string Startingtime { get; set; }
        public string Endingtime { get; set; }
        public Nullable<decimal> Amountforadults { get; set; }
        public Nullable<decimal> Amountforchildren { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public Nullable<decimal> Servicecharges { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Refoundamount { get; set; }
        public string Remarks { get; set; }
        public string StartingMinutes { get; set; }
        public string EndingMinutes { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
    }
}
