//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmrahCancellationPolicyHistory
    {
        public int Id { get; set; }
        public Nullable<int> UmrahCancellationPolicyId { get; set; }
        public Nullable<int> UmrahCancellationMatrixId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> OldValue { get; set; }
        public Nullable<int> NewValue { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Description { get; set; }
    }
}
