//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmrahPassenger
    {
        public int Id { get; set; }
        public Nullable<int> UmrahId { get; set; }
        public string GivenName { get; set; }
        public string SurName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Gender { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string MobileNumber { get; set; }
        public string GenderFlag { get; set; }
        public string IsActive { get; set; }
        public Nullable<bool> IsFoodRequired { get; set; }
        public Nullable<bool> IsBedRequired { get; set; }
        public Nullable<bool> IsWheelChairRequired { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
