//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWUmrahPackageDetail
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string RoomType { get; set; }
        public Nullable<long> AmountforAdult { get; set; }
        public Nullable<long> AmountforChild { get; set; }
        public Nullable<long> AmountforInfant { get; set; }
        public Nullable<int> NoofAdults { get; set; }
        public Nullable<int> NoofChilds { get; set; }
        public Nullable<int> NoofInfants { get; set; }
        public Nullable<int> RoomCharges { get; set; }
        public string RoomSharingType { get; set; }
        public Nullable<long> GST { get; set; }
        public Nullable<long> ExtraCharges { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<long> Advance { get; set; }
        public Nullable<long> Balance { get; set; }
        public string PaymentMode { get; set; }
        public string BankName { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> TravelStartDate { get; set; }
        public Nullable<System.DateTime> TravelEndDate { get; set; }
        public string PackageParticulars { get; set; }
        public string AadharNumber { get; set; }
        public string EmailId { get; set; }
        public string PANNumber { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsHotelRequired { get; set; }
        public string HotelType { get; set; }
        public string HotelCategory { get; set; }
        public Nullable<int> NoofRooms { get; set; }
        public Nullable<int> NoofDaysinMacca { get; set; }
        public string MaccaHotelName { get; set; }
        public string RoomNoinMacca { get; set; }
        public Nullable<System.DateTime> OutDateofMacca { get; set; }
        public Nullable<int> NoofDaysinMadeena { get; set; }
        public string MadeenaHotelName { get; set; }
        public Nullable<System.DateTime> InDateofMadeena { get; set; }
        public string RoomNoinMadeena { get; set; }
        public string PlacesofVisit { get; set; }
        public Nullable<bool> IsFlightBookingRequired { get; set; }
        public string DepartureAirlines { get; set; }
        public string DepartureFlightNo { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string ReturnAirlines { get; set; }
        public string ReturnFlightNo { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnTime { get; set; }
        public Nullable<bool> IsFoodBookingRequired { get; set; }
        public Nullable<bool> IsVisaRequired { get; set; }
        public string CustomerDiscType { get; set; }
        public Nullable<int> CustomerDiscount { get; set; }
        public string SubAgentName { get; set; }
        public string SubAgentNumber { get; set; }
        public Nullable<int> SubAgentCommission { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CancellationCharges { get; set; }
        public string CancellationRemarks { get; set; }
        public Nullable<long> RefundAmount { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public string CancelledByName { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<long> OfflineRefundAmount { get; set; }
        public string Status { get; set; }
        public string MobileNumber { get; set; }
        public string PassportNumber { get; set; }
    }
}
